$schema: https://azuremlschemasprod.azureedge.net/latest/environment.schema.json
name: infer-sklearn-diabetes
image: mcr.microsoft.com/azureml/minimal-ubuntu22.04-py310-cpu-inference:latest
inference_config:
  liveness_route:
    path: /health
    port: 5001
  readiness_route:
    path: /health
    port: 5001
  scoring_route:
    path: /score
    port: 5001
conda_file: |
  channels:
    - conda-forge
  dependencies:
    - python=3.10
    - pip
    - pip:
      - numpy
      - scikit-learn
      - joblib
      - azureml-inference-server-http
